# Generated by Django 3.0.2 on 2020-01-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorski', '0003_auto_20200123_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upisi',
            name='status',
            field=models.CharField(choices=[('enrolled', 'enrolled'), ('passed', 'passed')], max_length=8),
        ),
    ]
