# Generated by Django 3.0.2 on 2020-01-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorski', '0004_auto_20200123_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upisi',
            name='status',
            field=models.CharField(choices=[('enrolled', 'enrolled'), ('passed', 'passed'), ('not_passed', 'not_passed')], max_length=10),
        ),
    ]
