# Generated by Django 3.0.2 on 2020-01-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorski', '0005_auto_20200123_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmeti',
            name='kod',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
