# Generated by Django 3.0.2 on 2020-01-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0002_korisnici_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnici',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
