# Generated by Django 3.0.2 on 2020-01-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0003_auto_20200122_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnici',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
    ]
