# Generated by Django 3.0.2 on 2020-01-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0004_auto_20200123_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnici',
            name='role',
            field=models.CharField(default='student', max_length=7),
        ),
    ]
